# specify Docker base image
FROM bayesimpact/react-base

# the folder application within the container (prevents conflicts with OS folders)
WORKDIR  /usr/src/app

# install dependencies (copies 'from folder' --> 'destination folder')
COPY package.json /usr/src/app
RUN npm install

# copy application files (moved here to make use of Docker's cache machanism)
COPY . /usr/src/app

# startup command
CMD ["npm", "start"]

# open container port
EXPOSE 3000
