/* AUTH ACTIONS */
export const SIGNED_IN = 'SIGNED_IN';
export const SIGNED_IN_ERROR = 'SIGNED_IN_ERROR';
export const SIGNED_OUT = 'SIGNED_OUT';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

/* USER ACTIONS */
export const USER_LIST_FETCHED = 'USER_LIST_FETCHED';
export const USER_LIST_FETCHED_ERROR = 'USER_LIST_FETCHED_ERROR';

/* ALUNO ACTIONS */
export const ALUNO_LIST_FETCHED = 'ALUNO_LIST_FETCHED';
export const ALUNO_LIST_FETCHED_ERROR = 'ALUNO_LIST_FETCHED_ERROR';

/* PROFESSOR ACTIONS */
export const PROFESSOR_LIST_FETCHED = 'PROFESSOR_LIST_FETCHED';
export const PROFESSOR_LIST_FETCHED_ERROR = 'PROFESSOR_LIST_FETCHED_ERROR';
export const PROFESSOR_FETCHED = 'PROFESSOR_FETCHED';
export const PROFESSOR_FETCHED_ERROR = 'PROFESSOR_FETCHED';

/* UI ACTIONS */
export const SECTION_SELECTED = 'SECTION_SELECTED';
